models:
  - provider: openai
    model_name: gpt-4
    api_key: ''

  - provider: gemini
    model_name: gemini-2.5-flash
    api_key: ''

  - provider: ibmcloud
    model_id: ibm/granite-3-3-8b-instruct
    api_key: ''
    service_url: ''
    project_id: ''

#  - provider: huggingface
#    model_name: ibm-granite/granite-4.0-tiny-preview
#    task: text-generation
#    device: -1
#    token: 